application: emoodji
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

-url: /populate
  script: song_database.app

- url: .*
  script: main.py
 #object app in main.py

libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: latest
